defmodule ApiGit.Factory do
  use ExMachina.Ecto, repo: ApiGit.Repo

  alias ApiGit.User

  def user_params_factory do
    %{
      "senha" => "12345678"
    }
  end

  def user_factory do
    %User{
      id: "7c9e684f-be33-4593-946d-58f5bba2e0c2",
      senha: "12345678"
    }
  end

  # https://hexdocs.pm/ex_machina/2.3.0/readme.html#non-map-factories
  def user_repos_response_factory(_attrs) do
    ~s([
      {
        "id": 332934215,
        "node_id": "MDEwOlJlcG9zaXRvcnkzMzI5MzQyMTU=",
        "name": "beatlesquiz",
        "full_name": "mrinardo/beatlesquiz",
        "private": false,
        "owner": {
          "login": "mrinardo",
          "id": 36894221,
          "node_id": "MDQ6VXNlcjM2ODk0MjIx",
          "avatar_url": "https://avatars.githubusercontent.com/u/36894221?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/mrinardo",
          "html_url": "https://github.com/mrinardo",
          "followers_url": "https://api.github.com/users/mrinardo/followers",
          "following_url": "https://api.github.com/users/mrinardo/following{/other_user}",
          "gists_url": "https://api.github.com/users/mrinardo/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/mrinardo/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/mrinardo/subscriptions",
          "organizations_url": "https://api.github.com/users/mrinardo/orgs",
          "repos_url": "https://api.github.com/users/mrinardo/repos",
          "events_url": "https://api.github.com/users/mrinardo/events{/privacy}",
          "received_events_url": "https://api.github.com/users/mrinardo/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/mrinardo/beatlesquiz",
        "description": "Exemplo de aplicação de quiz com React e Next.js feito durante Imersão React da Alura",
        "fork": false,
        "url": "https://api.github.com/repos/mrinardo/beatlesquiz",
        "forks_url": "https://api.github.com/repos/mrinardo/beatlesquiz/forks",
        "keys_url": "https://api.github.com/repos/mrinardo/beatlesquiz/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mrinardo/beatlesquiz/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mrinardo/beatlesquiz/teams",
        "hooks_url": "https://api.github.com/repos/mrinardo/beatlesquiz/hooks",
        "issue_events_url": "https://api.github.com/repos/mrinardo/beatlesquiz/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mrinardo/beatlesquiz/events",
        "assignees_url": "https://api.github.com/repos/mrinardo/beatlesquiz/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mrinardo/beatlesquiz/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mrinardo/beatlesquiz/tags",
        "blobs_url": "https://api.github.com/repos/mrinardo/beatlesquiz/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mrinardo/beatlesquiz/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mrinardo/beatlesquiz/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mrinardo/beatlesquiz/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mrinardo/beatlesquiz/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mrinardo/beatlesquiz/languages",
        "stargazers_url": "https://api.github.com/repos/mrinardo/beatlesquiz/stargazers",
        "contributors_url": "https://api.github.com/repos/mrinardo/beatlesquiz/contributors",
        "subscribers_url": "https://api.github.com/repos/mrinardo/beatlesquiz/subscribers",
        "subscription_url": "https://api.github.com/repos/mrinardo/beatlesquiz/subscription",
        "commits_url": "https://api.github.com/repos/mrinardo/beatlesquiz/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mrinardo/beatlesquiz/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mrinardo/beatlesquiz/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mrinardo/beatlesquiz/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mrinardo/beatlesquiz/contents/{+path}",
        "compare_url": "httpsmrinardoxx://api.github.com/repos/mrinardo/beatlesquiz/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mrinardo/beatlesquiz/merges",
        "archive_url": "https://api.github.com/repos/mrinardo/beatlesquiz/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mrinardo/beatlesquiz/downloads",
        "issues_url": "https://api.github.com/repos/mrinardo/beatlesquiz/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mrinardo/beatlesquiz/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mrinardo/beatlesquiz/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mrinardo/beatlesquiz/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mrinardo/beatlesquiz/labels{/name}",
        "releases_url": "https://api.github.com/repos/mrinardo/beatlesquiz/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mrinardo/beatlesquiz/deployments",
        "created_at": "2021-01-26T01:23:26Z",
        "updated_at": "2021-01-30T16:21:40Z",
        "pushed_at": "2021-01-30T16:21:38Z",
        "git_url": "git://github.com/mrinardo/beatlesquiz.git",
        "ssh_url": "git@github.com:mrinardo/beatlesquiz.git",
        "clone_url": "https://github.com/mrinardo/beatlesquiz.git",
        "svn_url": "https://github.com/mrinardo/beatlesquiz",
        "homepage": "https://beatlesquiz.vercel.app/",
        "size": 178,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
      },
      {
        "id": 388448069,
        "node_id": "MDEwOlJlcG9zaXRvcnkzODg0NDgwNjk=",
        "name": "ignite_elixir_api_git",
        "full_name": "mrinardo/ignite_elixir_api_git",
        "private": false,
        "owner": {
          "login": "mrinardo",
          "id": 36894221,
          "node_id": "MDQ6VXNlcjM2ODk0MjIx",
          "avatar_url": "https://avatars.githubusercontent.com/u/36894221?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/mrinardo",
          "html_url": "https://github.com/mrinardo",
          "followers_url": "https://api.github.com/users/mrinardo/followers",
          "following_url": "https://api.github.com/users/mrinardo/following{/other_user}",
          "gists_url": "https://api.github.com/users/mrinardo/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/mrinardo/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/mrinardo/subscriptions",
          "organizations_url": "https://api.github.com/users/mrinardo/orgs",
          "repos_url": "https://api.github.com/users/mrinardo/repos",
          "events_url": "https://api.github.com/users/mrinardo/events{/privacy}",
          "received_events_url": "https://api.github.com/users/mrinardo/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/mrinardo/ignite_elixir_api_git",
        "description": "Challenge #1 Ignite Elixir module 6: Api GitHub Phoenix app",
        "fork": false,
        "url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git",
        "forks_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/forks",
        "keys_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/teams",
        "hooks_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/hooks",
        "issue_events_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/events",
        "assignees_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/tags",
        "blobs_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/languages",
        "stargazers_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/stargazers",
        "contributors_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/contributors",
        "subscribers_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/subscribers",
        "subscription_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/subscription",
        "commits_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/merges",
        "archive_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/downloads",
        "issues_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/labels{/name}",
        "releases_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mrinardo/ignite_elixir_api_git/deployments",
        "created_at": "2021-07-22T12:05:43Z",
        "updated_at": "2021-07-22T12:08:22Z",
        "pushed_at": "2021-07-22T12:08:17Z",
        "git_url": "git://github.com/mrinardo/ignite_elixir_api_git.git",
        "ssh_url": "git@github.com:mrinardo/ignite_elixir_api_git.git",
        "clone_url": "https://github.com/mrinardo/ignite_elixir_api_git.git",
        "svn_url": "https://github.com/mrinardo/ignite_elixir_api_git",
        "homepage": null,
        "size": 24,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Elixir",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main"
      }
      ])
  end
end
